name: build & publish artifacts

on:
  push:
    branches: [ release ]

jobs:
  publish_core_lib_nuget_source:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Ramos.ContentSecurityPolicy.NET/Ramos.ContentSecurityPolicy.NET.csproj
          PACKAGE_NAME: Ramos.ContentSecurityPolicy.NET
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

  publish_web_lib_nuget_source:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Ramos.ContentSecurityPolicy.NET.Web/Ramos.ContentSecurityPolicy.NET.Web.csproj
          PACKAGE_NAME: Ramos.ContentSecurityPolicy.NET.Web
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}