name: build & publish artifacts

on:
  push:
    branches: [ release ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"


jobs:
  publish_core_lib_nuget_source:
      name: Publish core lib to nuget source
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: >
          export VERSION=$(git describe --long --tags --match 'v*' | sed 's/v//' | sed -E 's/[-].+//g');
          echo $VERSION;
          dotnet pack --configuration Release --include-source -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true -p:Version=$VERSION -o out src/Neo.ContentSecurityPolicy.NET;
          cd out;
          dotnet nuget push Neo.ContentSecurityPolicy.NET.$VERSION.nupkg --force-english-output -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json;

  publish_web_lib_nuget_source:
      name: Publish web lib to nuget source
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: >
          export VERSION=$(git describe --long --tags --match 'v*' | sed 's/v//' | sed -E 's/[-].+//g');
          echo $VERSION;
          dotnet pack --configuration Release --include-source -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true -p:Version=$VERSION -o out src/Neo.ContentSecurityPolicy.NET.Web;
          cd out;
          dotnet nuget push Neo.ContentSecurityPolicy.NET.Web.$VERSION.nupkg --force-english-output -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json;